config/routes.rb
Rails.application.routes.draw do
  get "/", to: "site#index"

  authenticated :user do
    root to: 'users#show'
  end

  devise_for :users do
    get 'users/:id', to: 'users#show'
  end

  resources :users, only: [:show] do
    resources :bands,  only: :show do
      resources :concerts, only: [:index, :show]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :bands, except: [:new, :edit]
        patch "bands/unfavorite/:id", to: "bands#unfavorite"
        post "bands/search", to: "bands#search"
        post "bands/favorite_band", to: "bands#favorite_band"
    end
  end

end

app/models/band.rb
class Band < ActiveRecord::Base

	# include Modules::Concert_storer
	has_many :users, :through => :users_band
	has_many :users_band, dependent: :destroy
	has_many :concerts, dependent: :destroy
	validates :name, presence: true	
	validates :on_tour_until, presence: true
	# validates :description, presence: true

	def self.check_if_query_exists?(query, user, band)
		unless query.present?
			user.bands.push(band)
		end
		UsersBand.find_by(user_id: user.id, band_id: band.id)
	end

	def self.make_favorite(query)
		query.update_attribute(:is_favorite, true) unless query.is_favorite
	end

	def self.make_unfavorite(query)
		query.update_attribute(:is_favorite, false) unless !query.is_favorite
	end

	def save_concerts(events)
		events.uniq{|concert| concert[:date] }
		events.each do |event1| 
			events.each do |event2|
				if event1[:date] == event2[:date]
					event1.merge!(event2)
				end
			end
		end
		# binding.pry
		events.each do |event|
			self.concerts.create(
				date: event[:date].to_date.strftime("%a %d %b %Y"), 
				city: event[:city], 
				name: event[:name], 
				venue: event[:venue], 
				longitude: event[:lng].to_f, 
				latitude: event[:lat].to_f)
		end

	end

end


# filtered_events = {}
# 		binding.pry
# 		events.each do |item|  
# 		  if filtered_events.has_key? item[1]['date']
# 		    filtered_events[item[1]['date']].merge! item[1]
# 		  else
# 		    filtered_events[item[1]['date']] = item[1]
# 		  end
# 		end

app/models/concert.rb
class Concert < ActiveRecord::Base
	acts_as_mappable :default_units => :kms,
                   	 :default_formula => :sphere,
                     :distance_field_name => :distance,
                     :lat_column_name => :latitude,
                     :lng_column_name => :longitude
	belongs_to :band
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
has_many :bands, :through => :users_band
has_many :users_band
#validates :email, uniqueness: true
before_save { self.email = email.downcase }

validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }




	def calculate_distance(a,b)
		a.distance_to(b)
	end

  def self.user_favorite_bands(array)
    array.map do |id|
         Band.find(id)
      end

  end

  def self.favorite_bands(array)
      @user_favorite_bands = array.map do |id|
         Band.find_by(id: id)
      end
      @user_favorite_bands   
  end

  def add_band(band)
    self.bands.push(band)
  end
end

app/models/users_band.rb
class UsersBand < ActiveRecord::Base
	belongs_to :user
	belongs_to :band
end

app/controllers/api/v1/bands_controller.rb
class Api::V1::BandsController < ApplicationController
	def index
		render plain: "Hello"
	end

	def show
		@band = current_user.bands.find(params[:id])
	end

	def search
		apikey = "&apikey=Nvz5ypKtb8V40c3S"
		band_name = params[:band].downcase.titleize
		@band = Band.find_by(name: band_name)
		unless @band
			band_info = HTTParty.get("http://api.songkick.com/api/3.0/search/artists.json?query=#{band_name}#{apikey}")
			band = Band.create(name: band_info['resultsPage']['results']['artist'][0]['displayName'],
									on_tour_until: band_info['resultsPage']['results']['artist'][0]['onTourUntil'])
			#get band_id from songkick to make ajax call in order to get band concerts
			band_id = band_info['resultsPage']['results']['artist'][0]['id']

			concerts_information = HTTParty.get("http://api.songkick.com/api/3.0/artists/#{band_id}/calendar.json?#{apikey}")
			concerts = get_concerts_from(concerts_information)
			band.save_concerts(concerts)
			render json: {success: true, band: band}
		return
		end
		render json: {success: true, band: @band}
	end

	def create
		band = Band.create(
			name: params[:artistName],
			on_tour_until: params[:onTourUntil].to_date.strftime("%a %d %b %Y")
		)
		concerts = params['events']
		band.save_concerts(concerts)
		current_user.add_band(band)
		render json: band
	end

	def favorite_band
    	band = Band.find(params[:id])
    	query = UsersBand.find_by(user: current_user, band: band) || Band.check_if_query_exists?(query, current_user, band)
    	Band.make_favorite(query)
	 	 render json: band
	end

	def unfavorite
  	band = Band.find(params[:id])
		query = UsersBand.find_by(user: current_user, band: band)
		Band.make_unfavorite(query)
		#query.update_attribute(:is_favorite, false)
		render json: band
	end

	private

	def get_concerts_from(response)
		events = response['resultsPage']['results']['event']
			@concerts = []
			events.each_with_index do |event, index|
				@concerts.push({
					city: event['location']['city'],
					date: event['start']['date'],
					lat: event['location']['lat'],
					lng: event['location']['lng'],
					name: event['displayName'],
					venue: event['venue']['displayName']})
			end
			@concerts
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  unless Rails.env.development?
  	protect_from_forgery with: :exception
  end
  
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def index
  end
protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) << :name
	end

  def after_sign_in_path_for(resource)
    user_path(current_user) 
  end

  def disable_nav
    @disable_nav = true
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
	include Geokit::Geocoders

	def index
		user = User.find(params[:user_id])
		#@user_bands = Band.where("user_id = ?", @user.id)
		@user_bands = user.bands
	end
	
	def show
		@band = current_user.bands.find(params[:id])
		@concerts = @band.concerts
		a = Geokit::LatLng.new(@band.concerts[0].latitude,@band.concerts[0].longitude)
		b = Geokit::LatLng.new(@band.concerts[1].latitude,@band.concerts[1].longitude)
		@distance = a.distance_to(b)
		@city1 = @band.concerts[0].city
		@city2 = @band.concerts[1].city
		# binding.pry
	end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController

 def show
 end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	skip_before_action :authenticate_user!	
	before_filter :disable_nav, only: [:index]	
	
	def index
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include Geokit::Geocoders
 	before_action :authenticate_user!
 	before_filter :disable_nav, only: [:show]	

	def index
		@users = User.all
	end
	
	def show
		bands_ids_array =  UsersBand.where(user_id: current_user.id, is_favorite: true).pluck(:band_id)
		
		@user_favorite_bands = User.favorite_bands(bands_ids_array)
	
	 	@user_favorite_concerts = Array.new	 	
	 	@user_favorite_bands.each do |band|
	 		band.concerts.map do |concert|
	 			@user_favorite_concerts.push(concert)
	 		end
		end
		
		@concert_matches = Array.new
		for i in (0..@user_favorite_concerts.length) do 
			for j in (i+1..@user_favorite_concerts.length-1) do
				if @user_favorite_concerts[i].city == @user_favorite_concerts[j].city && @user_favorite_concerts[i].date == @user_favorite_concerts[j].date 
					@concert_matches.push(@user_favorite_concerts[i])
					@concert_matches.push(@user_favorite_concerts[j])
				end
			end
		end
	   @bands_matched = @concert_matches.map do |concert|
	   		Band.find_by(id: concert.band_id)
	   	end
	   	# binding.pry
	end

private

	def user_params
      params.require(:user).permit(:name, :email, :password, :password_controller)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/index.html.erb
<p>Good</p>
<div class="tile">
	<div class="home-header-video">
		<p>This</p>
	</div>
</div>

app/views/bands/index.html.erb
<h3>Nope</h3>

app/views/bands/show.html.erb
<h4>Band landing page </h4>
<p> <%= @band.name %> </p>
<p> Distance between A: <%= @city1 %>,  and B <%= @city2 %>, is <%= @distance %>kms.</p>
	<% @band.concerts.each do |concert| %>
	<li> <%=  link_to "#{concert.city}, the #{concert.date}", user_band_concert_path(current_user, @band, concert) %> </li>
	<% end %>
</ul>
</div>
</div>

app/views/concerts/show.html.erb
<p>hello</p>

app/views/layouts/_header.html.erb
<nav class="nav">
  <div class="nav-right nav-menu">
    <a class="nav-item" href="#">
      Home
    </a>
    <a class="nav-item" href="#">
      Documentation
    </a>
    <a class="nav-item" href="#">
      Blog
    </a>

    <span class="nav-item">
      <a class="button" >
        <span class="icon">
          <i class="fa fa-twitter"></i>
        </span>
        <span>Tweet</span>
      </a>
      <a class="button is-primary" href="#">
        <span class="icon">
          <i class="fa fa-download"></i>
        </span>
        <span>Download</span>
      </a>
    </span>
  </div>
</nav>

app/views/layouts/_landing.html.erb
<nav class="nav">
  <div class="nav-left">
    <a class="nav-item" href="#">
      <img src="/images/bulma.png" alt="Bulma logo}">
    </a>
  </div>

  <div class="nav-center">
    <a class="nav-item" href="#">
      <span class="icon">
        <i class="fa fa-github"></i>
      </span>
    </a>
    <a class="nav-item" href="#">
      <span class="icon">
        <i class="fa fa-twitter"></i>
      </span>
    </a>
  </div>

  <span class="nav-toggle">
    <span></span>
    <span></span>
    <span></span>
  </span>

  <div class="nav-right nav-menu">
    <a class="nav-item" href="#">
      Home
    </a>
    <a class="nav-item" href="#">
      Documentation
    </a>
    <a class="nav-item" href="#">
      Blog
    </a>

    <span class="nav-item">
      <a class="button" >
        <span class="icon">
          <i class="fa fa-twitter"></i>
        </span>
        <span>Tweet</span>
      </a>
      <a class="button is-primary" href="#">
        <span class="icon">
          <i class="fa fa-download"></i>
        </span>
        <span>Download</span>
      </a>
    </span>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Groopietravel</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial:"layouts/header"  unless @disable_nav %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/site/index.html.erb
<div id="back">

<div class="columns">
<div class="column is-12">
<section class="hero is-large">
      <video autoplay="" loop="" style="position:absolute">
        <source src="https://festrip.com/images/home/bg-home.mp4" type="video/mp4">
      </video>
    <!-- Hero content: will be in the middle -->
      <div class="hero-body">
        <div class="container has-text-centered">
          <h1 class="title is-1"><strong>GROOPIETRAVEL</strong></h1>
          <h2 class="title is-4">Don´t ever miss a concert</h2>
          <form class="guest-js-form" action="/users/sign_in">
          <div class="columns">
            <div class="column is-half is-offset-one-quarter">
            <p class="control">
<!--               <input type="text" class="input js-artist is-border-radius">
 -->            </p>
            <p class="control">
              <button type="submit" class="button js-submit is-fullwidth">Start your experience</button>
            </p>
            </div>
          </div>
        </form>
        </div>
      </div>
    </section>
  </div>
</div>
<!-- <section>
<div class="columns">
  <div class="column is-half is-offset-one-quarter">
  <div id="features" class="columns is-wrap">
    <div class="column is-half is-offset-one-quarter">
      <div class="">
        <p class="is-text-centered"><i class="fa fa-cog"></i></p>
        <h1 class="title is-3 is-text-centered">For all the music lovers</h1>
        <p class="content">
         Don´t ever miss a chance to follow your favorite bands while travelling around the world. Select your bands and see where and when are going to play...together!
        </p>
      </div>
    </div>
    </div>
  </div>
</div>
</section>
<div class="section">
</div>
<div class="name">
</div> -->
</div>

app/views/users/index.html.erb
<h3>This is the users index page</h3>
<nav class="nav has-shadow">
  <div class="container">
    <div class="nav-left">
      <a class="nav-item is-tab is-active">Card</a>
      <a class="nav-item is-tab">Level</a>
      <a class="nav-item is-tab">Media object</a>
      <a class="nav-item is-tab">Menu</a>
      <a class="nav-item is-tab">Message</a>
      <a class="nav-item is-tab">Modal</a>
      <a class="nav-item is-tab">Nav</a>
      <a class="nav-item is-tab">Pagination</a>
      <a class="nav-item is-tab">Panel</a>
      <a class="nav-item is-tab">Tabs</a>
    </div>
  </div>
</nav>

app/views/users/show.html.erb
<nav class="nav">
<nav class="nav-center">
  <!-- Left side -->

    <div class="navbar-item">
      <p class="title is-3 is-text-bold">
        <%=current_user.name %> 
      </p>
    </div>
  </nav>
  <nav class="nav-right">
  <%= link_to "Sign out", destroy_user_session_path, method: 'DELETE' %>
  </nav>
  </nav>
  <div class="columns is-dark">
    <div class="column is-two-thirds">
      <section class="section">
        <!-- <div class="columns is-wrap"> -->
          <div class="favorite-bands">
          <% @user_favorite_bands.each do |band| %>
            <div class="card">
						  <div class="card-image">
						    <figure class="image is-4by3">
						      <img src="/concert.jpeg" alt="band-image">
						    </figure>
						 		</div>
						  	<div class="card-content">
						    	<div class="media">
						      	<div class="media-content">
						        <p class="title is-5"><%= link_to band.name, user_band_path(current_user, band) %></p>
						      	<p class="subtitle is-7">Tour end: <%= band.on_tour_until %> </p>
						      	</div>
						    	</div>
							    <div class="content">
							      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
							      Phasellus nec iaculis mauris.      
							    </div>
							    <button type="submit" class="no-favorite" id="<%= band.id %>">Unfavorite</button>
						  </div>
						  <% end %>
					</div>
         <%  %>
         </div>
         <div class="column is-6">
				<% if @concert_matches != nil %>	
				<p>HEY! There was a match. Look at this!</p>
			<ul>
				<%	@concert_matches.each do |concert|	%>	
				<li> <%= "#{concert.name}, on #{concert.date} in #{concert.city}" %> 
				</li>
				<% end %>
			</ul>
			<% end %>
         </div>
       <!-- </div> -->
     </section>
     </div>
      <!-- <div class="column is-4"> -->
		    <div class="column is-one-third">
		    <section class="hero is-medium is-dark is-bold">
					<div class="hero-body">
    				<div class="container">
      				<h3 class="title">
       					Search for your favorite bands/artists</h3>
									<form class="js-form">
										<input type="text" class="js-artist">
										<button type="submit" class="js-submit">Search</button>
									</form>
							<div class="js-artist-name">
							</div>
							<p class="js-artist-ontour">On tour Until:</p>
					 </div>
  				</div>
				</section>
		      </div>
    		</div>
    		<div class="columns is-mobile">
				<div class="columns is-6">
				</div>
				<div class="columns is-6">
				</div>
    		</div>
    		<div class="container">
				<ul class="js-artist-nextdates"> 
					<li></li>
				</ul>
    		</div>
  

 





<%= link_to "Sign out", destroy_user_session_path, method: 'DELETE' %>